"""empty message

Revision ID: 7f288af5d6e5
Revises: 77a34ad3440b
Create Date: 2024-05-21 08:44:49.664804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f288af5d6e5'
down_revision = '77a34ad3440b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'weight')
    # ### end Alembic commands ###
