"""empty message

Revision ID: 85d708da4061
Revises: 58a13e0d3caf
Create Date: 2024-05-21 11:49:47.815252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d708da4061'
down_revision = '58a13e0d3caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_assign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['competitor'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_assign')
    # ### end Alembic commands ###
