service: hackaton2-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    image:
      name: appimage
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'